# Generated by Django 3.0.1 on 2019-12-26 01:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=100)),
                ('location', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BTC', models.FloatField(default=0)),
                ('USD', models.FloatField(default=0)),
                ('profile_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Trading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currencyStart', models.CharField(default='', max_length=100)),
                ('currencyEnd', models.CharField(default='', max_length=100)),
                ('trading_type', models.CharField(default='', max_length=100)),
                ('date', models.CharField(default='', max_length=100)),
                ('substractionAmount', models.FloatField(default=0)),
                ('ingressAmount', models.FloatField(default=0)),
                ('publisher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(default='', max_length=100)),
                ('date', models.CharField(default='', max_length=100)),
                ('currencyStart', models.CharField(default='', max_length=100, null=True)),
                ('currencyEnd', models.CharField(default='', max_length=100)),
                ('substractionAmount', models.FloatField(default=0)),
                ('ingressAmount', models.FloatField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
